### ISSUE TITLE
An Ecto integration example would be very helpful!

### ISSUE THREAD

**Issue by zipme** [Zatvobor/tirexs#141]

**Comment by Zatvobor** [comment]
It's definitely good for contribution. Don't you?

**Comment by Zatvobor** [comment]
I would like to start discussion here about possibility to provide an integration. Is there someone who supports this topic too?

**Comment by vishnuixm** [comment]
+1 I support this topic, it will very helpful

**Comment by Zatvobor** [comment]
:+1:

**Comment by baoist** [comment]
+1 I would love this.

**Comment by bulleric** [comment]
+1

**Comment by OpakAlex** [comment]
Tirexs it's not any db adapter, because Elasticsearch it's not a db.
http://take.ms/nfeVP

Why you need Ecto compatability? For what guys?

**Comment by zipme** [comment]
@OpakAlex Something like this? https://github.com/elastic/elasticsearch-rails/tree/master/elasticsearch-model

**Comment by OpakAlex** [comment]
Maybe you need rails, not phoenix? really, why you need phoenix? @zipme

**Comment by zipme** [comment]
@OpakAlex You made an assumption that I use phoenix, how do you know that? :trollface:

**Comment by OpakAlex** [comment]
@zipme i hope, @Zatvobor understand what i mean. He is one of the best engineers, and i hope tirexs never use ecto.

**Comment by zipme** [comment]
I know Tirexs is just a Elasticsearch client, maybe we can make another lib which utilizes Tirex?
Something like https://github.com/stavro/arc and https://github.com/stavro/arc_ecto

**Comment by zipme** [comment]
The title says "An Ecto integration example", it does not mean Tirex should use Ecto, but having an example of using Tirex TOGETHER with Ecto could be very useful ;)

**Comment by Zatvobor** [comment]
@OpakAlex, it's good to see that you're still staying on the bright side of engineering doctrine ) @zipme, agreed with you too. @lessless is about to contribute his own integration example. Hope, it would be helpful.

**Comment by OpakAlex** [comment]
any PR guys?

**Comment by OpakAlex** [comment]
or just speak for /dev/null ?

**Comment by lessless** [comment]
We are still working on it and will gladly share when it'll be ready

**Comment by Zatvobor** [comment]
nice

**Comment by OpakAlex** [comment]
![Preview](http://risovach.ru/upload/2015/04/mem/stalin-rasstrelyat_78621063_orig_.jpg)
