### ISSUE TITLE
Does Tirexs accepts a map (or a json blob) when bulk indexing?

### ISSUE THREAD

**Issue by kpanic** [Zatvobor/tirexs#151]
Hi,

I see that the API in the README is:

```
Tirexs.Bulk.store [index: "articles", refresh: true], settings do
  create id: 1, title: "One", tags: ["elixir"], type: "article"
  create id: 2, title: "Two", tags: ["elixir", "ruby"], type: "article"
  create id: 3, title: "Three", tags: ["java"], type: "article"
  create id: 4, title: "Four", tags: ["erlang"], type: "article"
end
```

I am wondering if it is possible to:
`Tirexs.Bulk.store  [index: "articles", refresh: true], settings, documents`

or something similar.
I saw that there's a public `bulk` here:
https://github.com/Zatvobor/tirexs/blob/7ca084d07714836931f0405668134cb77cdb1c88/lib/tirexs/bulk.ex#L30

Is it ok to use?

Thanks!

**Comment by kpanic** [comment]
@Zatvobor It turns out that I can do something like:

`[index: [id: 90, title: "barww"]]`

and:
`Tirexs.Bulk.store [index: "articles", refresh: true], settings, do: documents`

I am closing the issue :smile:

**Comment by Zatvobor** [comment]
Right.
