### ISSUE TITLE
Aggregation in favor of Facets

### ISSUE THREAD

**Issue by zdicesare** [Zatvobor/tirexs#155]
Tirexs appears to use Facets, which were [deprecated](https://www.elastic.co/guide/en/elasticsearch/reference/2.x/search-facets-migrating-to-aggs.html) and and were [removed](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_20_removed_features.html) in 2.0.

Has there been any thought to supporting aggregations in tirexs?

**Comment by Zatvobor** [comment]
Sounds good! Would you like to contribute?

**Comment by matrinox** [comment]
:+1: I think the first step is juts renaming `facets` to `aggs`. For the most part that works. I wouldn't mind contributing, we're working on aggregates right now
