### ISSUE TITLE
How to put settings?

### ISSUE THREAD

**Issue by kpanic** [Zatvobor/tirexs#159]
Hi,

I have something like:

```
 def bootstrap_index(index_name, doc_type) do
    index = [index: index_name, type: doc_type]

    settings do
      analysis do
        filter "edge_ngram", [type: "edgeNGram", min_gram: 1, max_gram: 15]
        analyzer "autocomplete_analyzer",
          [
            filter: ["icu_normalizer", "icu_folding", "edge_ngram"],
            tokenizer: "icu_tokenizer"
          ]
      end
    end

    mappings do
      indexes "country", type: "string"
      indexes "city", type: "string"
      indexes "suburb", type: "string"
      indexes "road", type: "string"
      indexes "postcode", type: "string", index: "not_analyzed"
      indexes "housenumber", type: "string", index: "not_analyzed"
      indexes "coordinates", type: "geo_point"
      indexes "full_address", type: "string"
    end

    {:ok, _, _} = Tirexs.Mapping.create_resource(index)
end
```

However I am wondering how to populate the `settings` in Elasticsearch defined with the `settings` macro. I am surely missing something really simple :) thank you!

PS: mapping works perfectly

**Comment by kpanic** [comment]
I found out that I can do:
`Tirexs.ElasticSearch.put(index_name, JSX.encode!(index[:settings]), settings)`
However I am for missing a piece here :)

**Comment by kpanic** [comment]
@Zatvobor if you feel that mappings + settings should be created in one shot (at index creation time) I can give it a go to change the code in tirexs. Please let me know, thank you!

**Comment by Zatvobor** [comment]
Personally, I'm not sure about that. However, let's try this approach.
