### ISSUE TITLE
Call query methods outside of search block

### ISSUE THREAD

**Issue by matrinox** [Zatvobor/tirexs#173]
When you get a query pyramid like this...

```elixir
  search [index: "index"] do
    query do
      filtered do
        filter do
          terms "field", [1,2,3]
        end
      end
    end
    order do
      ...
    end
    facets do
      ...
    end
  end
```

...you wish you can break it up. So the first way to do this would be via functions. Can't seem to do it, get undefined function errors.

This also means that you can't create custom methods to dynamically generate queries like the following:

```elixir
def add_filters(filters) do
  Enum.map filters, fn ({key, value}) ->
    filter do
      terms key, values
    end
  end
end
```

Am I missing something or is there no way to create queries beyond static ones? I was hoping that these functions would just return keyword lists and would just work regardless of where it was called.

**Comment by OpakAlex** [comment]
@matrinox you can use just list structure, like
```
filters: [
  and: [
  [term: "some1"],
  [term: "some2"]
  ]
]
```

And just do http request.
