### ISSUE TITLE
Deprications using examples in readme

### ISSUE THREAD

**Issue by triptec** [Zatvobor/tirexs#188]
Using
Tirexs.Query.create_resource(articles) gives:
warning: `Tirexs.Elasticsearch.config/0` is deprecated, please use `Tirexs.get_uri_env/0` instead

and:

warning: `Tirexs.Elasticsearch.post/3` is deprecated, please use `Tirexs.HTTP.post/3` instead

**Comment by Zatvobor** [comment]
Correct. This is because you're running a `-beta` version, which is under development and available just only as a preview. The next step would be removing all of them in `v0.8.0`. There is a stable release `v0.7.6`. Use its for getting things done )
