### ISSUE TITLE
> 0.7.4: Tirexs.ElasticSearch.config returns nil

### ISSUE THREAD

**Issue by kpanic** [Zatvobor/tirexs#193]
Steps to reproduce:

1. `mix new aproject`
2. `cd aproject`
3. add tirexs 0.7.6 in mix.exs
4. `mix do deps.get, deps.compile`
5. `iex -S mix`
6. `require Tirexs.ElasticSearch`
7. `Tirexs.Elasticsearch.config`

which results in `nil`

I did not yet investigated why and if it's a problem with my environment

in 0.7.4 `Tirexs.Elasticsearch.config` seems to be fine

Also if I run iex -S mix in the `0.7.6` tag branch I get a correct URI struct when executing `Tirexs.Elasticsearch.config`

**Comment by kpanic** [comment]
oops, I think I forgot to put `:tirexs` in the list of applications in `mix.exs`

**Comment by kpanic** [comment]
My fault, closing the issue

**Comment by Zatvobor** [comment]
related PR, #194
