### ISSUE TITLE
Elastic search server behind reverse proxy  ssl support?

### ISSUE THREAD

**Issue by bulleric** [Zatvobor/tirexs#214]
Hallo Tirexs community ;)

i got a strange problem with my elasticSearch setup.
I use an nginx reverse proxy with elastic search server with an ssl certificate.
but the creation of a bulk store gives me always a http:400 response.

## Setup
Phoenix Framework
Elastic Search Server
Nginx Reverse Proxy
SSL Certificate 

## my config:
settings = Tirexs.ElasticSearch.config() {:config, "search.my-search-server-domain.com:443", 443, "search.gastro smart.com",  "https"}

## the response error:
{:error, 400,
 "<html>\r\n<head><title>400 The plain HTTP request was sent to HTTPS port</title></head>\r\n<body bgcolor=\"white\">\r\n<center>_400 Bad Request_</center>\r\n<center>The plain HTTP request was sent to HTTPS port</center>\r\n<hr><center>nginx/1.4.6 (Ubuntu)</center>\r\n</body>\r\n</html>\r\n"} #

is SSL supported?

Best Regards

Eric

**Comment by Zatvobor** [comment]
Looks like the issue on your side. Here is my proof.

```shell
➜  tirexs git:(master) ✗ iex -S mix
iex(1)> Tirexs.HTTP.get("https://bitcoin.toshi.io/api/v0/toshi.json")
{:ok, 200,
 %{blocks: %{main_count: 403892, orphan_count: 7, side_count: 356},
   database: %{size: "785 GB"}, peers: %{available: 18692, connected: 3},
   status: "active",
   transactions: %{count: 86246200, unconfirmed_count: 870423}}}
```
or, through merging users URI with default
```bash
➜  tirexs git:(master) ✗ iex -S mix
iex(1)> Tirexs.HTTP.get("/api/v0/toshi.json", %URI{ scheme: "https", host: "bitcoin.toshi.io", port: 443 })
{:ok, 200,
 %{blocks: %{main_count: 403893, orphan_count: 7, side_count: 356},
   database: %{size: "785 GB"}, peers: %{available: 18692, connected: 3},
   status: "active",
   transactions: %{count: 86246200, unconfirmed_count: 870423}}}
```

as you can see, all works as needed. Or I miss something? FF to drop a line here if you still experiencing the issue. Thanks.
