### ISSUE TITLE
Boosting by field value (i.e. popularity)

### ISSUE THREAD

**Issue by ashleyw** [Zatvobor/tirexs#219]
https://www.elastic.co/guide/en/elasticsearch/guide/current/boosting-by-popularity.html

Is this currently possible using tirexs?

Thanks!

**EDIT:** It appears `custom_filters_score` was previously able to accomplish this, but it was deprecated in 0.90.4 in favor of `function_score`: https://www.elastic.co/guide/en/elasticsearch/reference/0.90/query-dsl-custom-filters-score-query.html

**Comment by Zatvobor** [comment]
Well done!
