### ISSUE TITLE
call appropriate Tirexs.HTTP.post/3 function.

### ISSUE THREAD

**Issue by kenta-aktsk** [Zatvobor/tirexs#222]
Hi, in `Tirexs.ElasticSearch.Settings.create_resource/2` function, `Tirexs.HTTP.post/3` function is called like below:

```elixir
HTTP.post(definition[:index], to_resource_json(definition), uri)
```

When `Tirexs.HTTP.post/3` function is called like above, following phrase will be called.

```elixir
  def post(path, params, %URI{} = uri) when is_binary(path) do
    do_request(:post, url(path, params, uri))
  end
```

I think this is wrong call. No error occurred but no settings can be created. We should pass body parameter to post method.

So I think you should fix `Tirexs.ElasticSearch.Settings.create_resource/2` like below:

```elixir
HTTP.post(definition[:index], uri, to_resource_json(definition))
```

I'm not sure my opinion is right or wrong.
But after fixing like above, it worked fine. (settings was successfully created)

**Comment by Zatvobor** [comment]
Well done. Thanks for contribution dude.
