### ISSUE TITLE
Ecto 2.0 compatability

### ISSUE THREAD

**Issue by lessless** [Zatvobor/tirexs#225]
Hello, 

Are  there any known nuances with upcoming Ecto 2.0? We're using `ecto 2.0-rc5` (latest atm) and very simple mapping (this is a whole file, no module definition whatsoever)

```
# properties/mapping.ex

  Tirexs.DSL.define(fn() ->
    alias App.Property
    alias App.ESRepo

    import Tirexs.Mapping
    index = [ type: ESRepo.type_name(%Property{}), index: ESRepo.index_name(%Property{})]

   mappings do
      indexes "title",       type: "string"
      indexes "description", type: "object"
    end

  index end)
```

yielding following error during the compilation phase 

```
** (FunctionClauseError) no function clause matching in Tirexs.ENV.__unwrap__/1
    lib/tirexs/env.ex:66: Tirexs.ENV.__unwrap__(nil)
    lib/tirexs/dsl.ex:53: Tirexs.DSL.create_resource/1
    (elixir) lib/kernel/parallel_compiler.ex:100: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/8
```

**Comment by Zatvobor** [comment]
May I ask you to contribute your example right here, #141. Thanks.

**Comment by lessless** [comment]
@Zatvobor we don't have a production experience yet but I can share our progress so far. Basically, as Ecto 2.0 deprecates `Ecto.Model` in favor of `Ecto.Schema` all Ecto entities are now  plain structs and it's super easy to roll a simple repo on top of `Tirexs.HTTP`.
As of using writing real `Ecto.Repository` adapter to use Elastic as primary storage  it's a pure suicide mission unless at least v5.5 due to known resiliency problems.

**Comment by Zatvobor** [comment]
Nice. Let's keep in touch.

**Comment by codecakes** [comment]
@lessless are you guys interfacing ecto ontop of tirexs

**Comment by OpakAlex** [comment]
))) why you need interface for http?)))))

**Comment by lessless** [comment]
Nah, it'll be overcomplication. Just imagine a maintenance burden to keepin
sync fast-pace  changing Elastic API and DSL to support it :)
