### ISSUE TITLE
Need to fix warnings for elixir 1.3

### ISSUE THREAD

**Issue by TakteS** [Zatvobor/tirexs#232]
When we use the latest elixir version, we have a lot of warnings from tirexs on compilation stage. What do you think about this? I think I can help you to fix it at this week

**Comment by Zatvobor** [comment]
Yes, you can. It would be helpful for community. 

I'm running out of my schedule a little bit, so I can't manage it asap.

**Comment by Zatvobor** [comment]
@TakteS, there is available PR #230. So, you can start from there.

Thanks

**Comment by Zatvobor** [comment]
@TakteS, any updates here?
