### ISSUE TITLE
Configuring multiple ES hosts

### ISSUE THREAD

**Issue by safwank** [Zatvobor/tirexs#251]
Apologies if this is not the right forum to ask questions, but is there a convenient way of specifying multiple ES hosts in `config`? Looking at [this](https://github.com/Zatvobor/tirexs/blob/master/lib/tirexs/env.ex) it might be possible to override the default host in each call. Is this correct? If not, is there a better way?

**Comment by OpakAlex** [comment]
@safwank check how to do http requests. This is not tirexs issue, we don't support cases with 10x ES hosts. If you need something custom do it, it's just http: https://en.wikipedia.org/wiki/Hypertext_Transfer_Protocol

**Comment by safwank** [comment]
I understand it's not an issue, it's indeed a question. I'm just asking if `tirexs` supports the said scenario. If not, it's not a big deal. Really.

**Comment by safwank** [comment]
If there's a better forum to ask this sort of questions, let me know. Being sarcastic and unhelpful doesn't help.

**Comment by OpakAlex** [comment]
@safwank I answered on your question very good, because it's just http, nothing more, nothing less.
