### ISSUE TITLE
Support Elixir 1.4

### ISSUE THREAD

**Issue by rawkode** [Zatvobor/tirexs#259]
```
warning: the dependency :tirexs requires Elixir "~> 1.3.0" but you are running on v1.4.1
```

**Comment by OpakAlex** [comment]
@rawkode yes, looks like this. We  need support 1.4? 1.3 so shit?))))))))

**Comment by rawkode** [comment]
I'm not sure why this is closed?

**Comment by OpakAlex** [comment]
@rawkode if you want fix it make PR. We use 1.3 for apps. It's works without warning ;)

**Comment by Luciam91** [comment]
+1 on allowing the use of 1.4, libraries shouldn't limit application uses

**Comment by OpakAlex** [comment]
make PR @Luciam91  ;) You are welcome.
