### ISSUE TITLE
Problem when attempting to delete an entire index

### ISSUE THREAD

**Issue by Qqwy** [Zatvobor/tirexs#264]
This gives me back `:error`:

```elixir
Tirexs.HTTP.delete("/my_index")
```
and the index in ElasticSearch is not deleted.

However, doing this manually works:
```
curl -X DELETE \
  http://localhost:9200/my_index \
```

What is going on here? This seems like a bug in Tirexs to me.

**Comment by OpakAlex** [comment]
@Qqwy try debug it local and write test for your ES version and Tirexs. Thanks a lot

**Comment by Zatvobor** [comment]
It's related to #263 (follow that ticket)
