### ISSUE TITLE
Connecting to cluster

### ISSUE THREAD

**Issue by ulutomaz** [Zatvobor/tirexs#271]
Hi, 

I am having difficulties finding how to configure a connection to a cluster? 

T.

**Comment by OpakAlex** [comment]
Hello, can you  add cluster url into config?

**Comment by ulutomaz** [comment]
Hmm... what exactly is cluster url?

**Comment by OpakAlex** [comment]
https://www.elastic.co/guide/en/elasticsearch/guide/current/distributed-cluster.html

```
With most databases, scaling horizontally usually requires a major overhaul of your application to take advantage of these extra boxes. In contrast, Elasticsearch is distributed by nature: it knows how to manage multiple nodes to provide scale and high availability. This also means that your application doesn’t need to care about it.
```

`This also means that your application doesn’t need to care about it.`

**Comment by ulutomaz** [comment]
Ok. So in my config/config.exs I only specify 

config :tirexs, :uri, "http://<IP of 1 of the nodes>:9200"

but in the case that this node (from within cluster setup) fails for some reason, my app stop responding since I have only 1 ip. Ok I assume I have to somehow find a way to manualy swith to another node IP...

**Comment by OpakAlex** [comment]
@ulutomaz  you need read about how to configure cluster in ES. because it's not issue in tirexs. It's just issue with cluster ES.

**Comment by ulutomaz** [comment]
I've already configured a cluster. I don't have problems with this. My only problem is how to provide continuance of working, since in a way that tirex is configured now (with me) this can't be done. See my previous comment. I will either use DNS (if routing is supported) or Load balancer. Anyway thanks for your work on tirexs.
