### ISSUE TITLE
Tirexs.HTTP.delete("/my_index") does not work as expected

### ISSUE THREAD

**Issue by Electron-libre** [Zatvobor/tirexs#275]
```Tirexs.HTTP.delete("/my_index")``` returns
```:error```

The expected behaviour would be to delete the index as
```HTTPoison.delete(url("/index")```
does.

**Comment by sebastialonso** [comment]
I usually get the `:error` error (for lack of a better word) when Tirexs can't connect to the Elastic instance.

can you confirm this isn't the case?

**Comment by Electron-libre** [comment]
Hi, sorry I can't reproduce anymore, I moved away from ES.
