### ISSUE TITLE
Dependency Warning for Elixir 1.5.1

### ISSUE THREAD

**Issue by juddey** [Zatvobor/tirexs#279]
Hello! Just installed this lib, got a dependency warning:

`warning: the dependency :tirexs requires Elixir "~> 1.3.0 or ~> 1.4.1" but you are running on v1.5.1`

Am I just being silly or is all that is required is to bump the dep to 1.5.1 and run tests to make sure nothing else is broken?

If so, would be happy to take a stab at a PR. (First elixir one, but have PR'd to other codebases before)

**Comment by OpakAlex** [comment]
worked with 1.7.4 elixir at 6.6.2 branch.
