### ISSUE TITLE
How can I count results given by a query?

### ISSUE THREAD

**Issue by sebastialonso** [Zatvobor/tirexs#284]
According to [this](https://github.com/Zatvobor/tirexs/commit/72fc7b039601d869842e88c78573344867f4d0b0) commit this was possible using the Tirexs.Manage module, but apparently it no longer exists. 
Is this functionality still available?

Hitting the "/_count" endpoint is still available but how can I pass advanced queries, like
`[query: [bool: [must: [[match: [active: true]]], should: nil]]]`, to the get function? I have tried many many ways, I have looked at the code, but I'm not sure if it's possible.

Thanks!

**Comment by sebastialonso** [comment]
OK, according to the official Elastic [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-count.html), both GET and POST can be used to query per count, given that not all clients allow GET with body.

Actually passing the query element as params into the Tirexs.HTTP.post method works!

Great library!

**Comment by OpakAlex** [comment]
just `curl http://elasticsearch-host:9200/index-name/_count`
