### ISSUE TITLE
Creating mapping doesn't work for 6+

### ISSUE THREAD

**Issue by matbox** [Zatvobor/tirexs#285]
Does anyone have luck in trying to use  

`Tirexs.Mapping.create_resource(index)` 

in Elasticsearch 6+? I always end up getting

`{:error, 400, %{error: %{reason: "unknown setting [index.index] did you mean [index.codec]?", root_cause: [%{reason: "unknown setting [index.index] did you mean [index.codec]?", type: "illegal_argument_exception"}], type: "illegal_argument_exception"}, status: 400}}`

Thanks,
Matthias

**Comment by sebastialonso** [comment]
Same bug. Only solution was to revert back to version 6.0.0.

If I have more time this week, I could read through the breaking changes on the new versions of Elastic and try to find the problem. Can you tell me the version you were using?

**Comment by OpakAlex** [comment]
Fixed into 6.6.2 branch.
